/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author ASUS
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    private String result = "";
    private double firstValue = 0;
    private double secondValue = 0;
    private String xyz="";
    private String zyx="";
    
    private String operation ="";
    private boolean valueCheck = true;
    
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextDisplay = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonPlusMinus = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonPersentage = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonMultiple = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(null);

        jTextDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextDisplay);
        jTextDisplay.setBounds(18, 23, 400, 50);

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonClear.setText("AC");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear);
        jButtonClear.setBounds(18, 90, 72, 37);

        jButtonPlusMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPlusMinus.setText("+/-");
        jButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusMinusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPlusMinus);
        jButtonPlusMinus.setBounds(125, 90, 72, 37);

        jButtonDivision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDivision.setText("/");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDivision);
        jButtonDivision.setBounds(346, 90, 70, 37);

        jButtonPersentage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPersentage.setText("%");
        jButtonPersentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersentageActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPersentage);
        jButtonPersentage.setBounds(240, 90, 70, 37);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 160, 70, 37);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(130, 160, 70, 37);

        jButtonMultiple.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMultiple.setText("*");
        jButtonMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiple);
        jButtonMultiple.setBounds(346, 157, 70, 37);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(240, 160, 70, 37);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 230, 70, 37);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(130, 230, 70, 37);

        jButtonMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinus);
        jButtonMinus.setBounds(346, 224, 70, 37);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(240, 230, 70, 37);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 290, 70, 37);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 290, 70, 37);

        jButtonPlus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPlus);
        jButtonPlus.setBounds(346, 288, 70, 37);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 290, 70, 37);

        jButton0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0);
        jButton0.setBounds(18, 357, 180, 37);

        jButtonDot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDot);
        jButtonDot.setBounds(240, 357, 70, 37);

        jButtonEqual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEqual);
        jButtonEqual.setBounds(346, 357, 70, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
            jTextDisplay.setText(jTextDisplay.getText() + "1");
        }else{
            jTextDisplay.setText("1");
            this.valueCheck = true;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
            jTextDisplay.setText(jTextDisplay.getText() + "2");
        }else{
            jTextDisplay.setText("2");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + "3");
        }else{
            jTextDisplay.setText("3");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + "4");
        }else{
            jTextDisplay.setText("4");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        if(!this.jTextDisplay.getText().equals("")){
            if(valueCheck){
                jTextDisplay.setText(jTextDisplay.getText() + "0");
            }else{
                jTextDisplay.setText("0");
                this.valueCheck = true;
            }
        }
        
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + "5");
        }else{
            jTextDisplay.setText("5");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + "6");
        }else{
            jTextDisplay.setText("6");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(this.operation.equals("")){
        jTextDisplay.setText(jTextDisplay.getText() + "7");
        }else{
            jTextDisplay.setText("7");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + "8");
        }else{
            jTextDisplay.setText("8");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + "9");
        }else{
            jTextDisplay.setText("9");
            this.valueCheck = true;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
        if(valueCheck){
        jTextDisplay.setText(jTextDisplay.getText() + ".");
        }else{
            jTextDisplay.setText(".");
            this.valueCheck = true;
        }
        
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextDisplay.setText("");
        this.valueCheck = true;
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            this.firstValue = Double.parseDouble(jTextDisplay.getText());
            this.operation = "+";
             jTextDisplay.setText("+");
             this.valueCheck = false;
        }
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            this.valueCheck = false;
            this.secondValue =  Double.parseDouble(jTextDisplay.getText());
            if(this.operation.equals("+")){
                jTextDisplay.setText(String.valueOf(this.firstValue+this.secondValue));
            }
            if(this.operation.equals("-")){
                
                jTextDisplay.setText(String.valueOf(this.firstValue-this.secondValue));
            }
            if(this.operation.equals("/")){
                jTextDisplay.setText(String.valueOf(this.firstValue/this.secondValue));
            }
            if(this.operation.equals("*")){
                jTextDisplay.setText(String.valueOf(this.firstValue*this.secondValue));
            }
            this.operation = "=";
        }
        
        
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            this.firstValue = Double.parseDouble(jTextDisplay.getText());
            this.operation = "-";
             jTextDisplay.setText("-");
             this.valueCheck = false;
        }
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipleActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            this.firstValue = Double.parseDouble(jTextDisplay.getText());
            this.operation = "*";
             jTextDisplay.setText("*");
             this.valueCheck = false;
        }
    }//GEN-LAST:event_jButtonMultipleActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            this.firstValue = Double.parseDouble(jTextDisplay.getText());
            this.operation = "/";
             jTextDisplay.setText("/");
             this.valueCheck = false;
        }
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusMinusActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            double a = Double.parseDouble(jTextDisplay.getText());
            jTextDisplay.setText(String.valueOf(a * -1));
        }
       
    }//GEN-LAST:event_jButtonPlusMinusActionPerformed

    private void jButtonPersentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersentageActionPerformed
        // TODO add your handling code here:
        if(!jTextDisplay.getText().equals("")){
            double a = Double.parseDouble(jTextDisplay.getText());
            jTextDisplay.setText(String.valueOf(a / 100));
        }
    }//GEN-LAST:event_jButtonPersentageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiple;
    private javax.swing.JButton jButtonPersentage;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPlusMinus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDisplay;
    // End of variables declaration//GEN-END:variables
}
